/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'tag' : string,
  'city' : string,
  'line1' : string,
  'line2' : string,
  'state' : string,
  'pincode' : string,
}
export interface Banner {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'image' : ExternalBlob,
}
export type BlogId = bigint;
export interface BlogInput {
  'status' : BlogStatus,
  'title' : string,
  'content' : string,
  'slug' : string,
  'author' : string,
  'coverImage' : [] | [ExternalBlob],
  'excerpt' : string,
  'category' : string,
}
export interface BlogPost {
  'id' : BlogId,
  'status' : BlogStatus,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'slug' : string,
  'author' : string,
  'coverImage' : [] | [ExternalBlob],
  'updatedAt' : bigint,
  'excerpt' : string,
  'category' : string,
}
export type BlogStatus = { 'published' : null } |
  { 'draft' : null };
export interface CustomerInfo {
  'city' : string,
  'name' : string,
  'email' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phone' : string,
  'pincode' : string,
}
export interface DailyAnalytics {
  'revenue' : bigint,
  'date' : bigint,
  'orderCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface InvoiceData {
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'codSurcharge' : bigint,
  'customer' : CustomerInfo,
  'gstNumber' : string,
  'orderDate' : bigint,
  'gstAmount' : bigint,
  'orderId' : bigint,
  'totalAmount' : bigint,
  'companyName' : string,
  'items' : Array<OrderItem>,
  'companyAddress' : string,
  'subtotal' : bigint,
}
export interface Order {
  'id' : bigint,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'codSurcharge' : bigint,
  'customer' : CustomerInfo,
  'orderStatus' : OrderStatus,
  'userId' : [] | [Principal],
  'createdAt' : bigint,
  'gstAmount' : bigint,
  'razorpayOrderId' : [] | [string],
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export type OrderId = bigint;
export interface OrderInput {
  'paymentMethod' : PaymentMethod,
  'customer' : CustomerInfo,
  'razorpayOrderId' : [] | [string],
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'name' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Cancelled' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'COD' : null } |
  { 'Razorpay' : null };
export type PaymentStatus = { 'Failed' : null } |
  { 'Refunded' : null } |
  { 'Paid' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : bigint,
  'status' : ProductStatus,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'stock' : bigint,
  'isBestseller' : boolean,
  'category' : ProductCategory,
  'isNew' : boolean,
  'price' : bigint,
  'image1' : [] | [ExternalBlob],
  'image2' : [] | [ExternalBlob],
  'image3' : [] | [ExternalBlob],
  'image4' : [] | [ExternalBlob],
  'image5' : [] | [ExternalBlob],
  'image6' : [] | [ExternalBlob],
}
export type ProductCategory = { 'Skincare' : null } |
  { 'Haircare' : null } |
  { 'Makeup' : null };
export type ProductId = bigint;
export interface ProductInput {
  'status' : ProductStatus,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'isBestseller' : boolean,
  'category' : ProductCategory,
  'isNew' : boolean,
  'price' : bigint,
  'image1' : [] | [ExternalBlob],
  'image2' : [] | [ExternalBlob],
  'image3' : [] | [ExternalBlob],
  'image4' : [] | [ExternalBlob],
  'image5' : [] | [ExternalBlob],
  'image6' : [] | [ExternalBlob],
}
export interface ProductRating {
  'productId' : bigint,
  'averageRating' : bigint,
  'reviewCount' : bigint,
}
export type ProductStatus = { 'active' : null } |
  { 'inactive' : null };
export interface Review {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'text' : string,
  'productId' : bigint,
  'rating' : bigint,
  'image1' : [] | [ExternalBlob],
  'image2' : [] | [ExternalBlob],
  'image3' : [] | [ExternalBlob],
}
export type ReviewId = bigint;
export interface ReviewInput {
  'text' : string,
  'productId' : bigint,
  'rating' : bigint,
  'image1' : [] | [ExternalBlob],
  'image2' : [] | [ExternalBlob],
  'image3' : [] | [ExternalBlob],
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'addresses' : Array<Address>,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAddress' : ActorMethod<[Address], boolean>,
  'adminAddBanner' : ActorMethod<[string, ExternalBlob], Banner>,
  'adminCreateBlogPost' : ActorMethod<[BlogInput], BlogPost>,
  'adminCreateProduct' : ActorMethod<[ProductInput], Product>,
  'adminDeleteBanner' : ActorMethod<[bigint], boolean>,
  'adminDeleteBlogPost' : ActorMethod<[BlogId], boolean>,
  'adminDeleteProduct' : ActorMethod<[ProductId], boolean>,
  'adminGetAnalytics' : ActorMethod<[], Array<DailyAnalytics>>,
  'adminListAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'adminListAllOrders' : ActorMethod<[], Array<Order>>,
  'adminUpdateBlogPost' : ActorMethod<[BlogId, BlogInput], [] | [BlogPost]>,
  'adminUpdateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'adminUpdateProduct' : ActorMethod<[ProductId, ProductInput], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chatbotQuery' : ActorMethod<[string], string>,
  'createOrder' : ActorMethod<[OrderInput], Order>,
  'createReview' : ActorMethod<[ReviewInput], Review>,
  'deleteReview' : ActorMethod<[ReviewId], boolean>,
  'getBestsellers' : ActorMethod<[], Array<Product>>,
  'getBlogPost' : ActorMethod<[BlogId], [] | [BlogPost]>,
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvoice' : ActorMethod<[OrderId], [] | [InvoiceData]>,
  'getNewArrivals' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductRating' : ActorMethod<[ProductId], ProductRating>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveProducts' : ActorMethod<[], Array<Product>>,
  'listBanners' : ActorMethod<[], Array<Banner>>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listReviewsByProduct' : ActorMethod<[ProductId], Array<Review>>,
  'lookupPincode' : ActorMethod<[string], string>,
  'removeAddress' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'updatePaymentStatus' : ActorMethod<
    [OrderId, PaymentStatus, [] | [string]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];