/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Address = IDL.Record({
  'tag' : IDL.Text,
  'city' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'state' : IDL.Text,
  'pincode' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Banner = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'image' : ExternalBlob,
});
export const BlogStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const BlogInput = IDL.Record({
  'status' : BlogStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const BlogId = IDL.Nat;
export const BlogPost = IDL.Record({
  'id' : BlogId,
  'status' : BlogStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'updatedAt' : IDL.Int,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const ProductStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'Skincare' : IDL.Null,
  'Haircare' : IDL.Null,
  'Makeup' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'status' : ProductStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'isBestseller' : IDL.Bool,
  'category' : ProductCategory,
  'isNew' : IDL.Bool,
  'price' : IDL.Nat,
  'image1' : IDL.Opt(ExternalBlob),
  'image2' : IDL.Opt(ExternalBlob),
  'image3' : IDL.Opt(ExternalBlob),
  'image4' : IDL.Opt(ExternalBlob),
  'image5' : IDL.Opt(ExternalBlob),
  'image6' : IDL.Opt(ExternalBlob),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProductStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'isBestseller' : IDL.Bool,
  'category' : ProductCategory,
  'isNew' : IDL.Bool,
  'price' : IDL.Nat,
  'image1' : IDL.Opt(ExternalBlob),
  'image2' : IDL.Opt(ExternalBlob),
  'image3' : IDL.Opt(ExternalBlob),
  'image4' : IDL.Opt(ExternalBlob),
  'image5' : IDL.Opt(ExternalBlob),
  'image6' : IDL.Opt(ExternalBlob),
});
export const ProductId = IDL.Nat;
export const DailyAnalytics = IDL.Record({
  'revenue' : IDL.Nat,
  'date' : IDL.Int,
  'orderCount' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Refunded' : IDL.Null,
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'COD' : IDL.Null,
  'Razorpay' : IDL.Null,
});
export const CustomerInfo = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'codSurcharge' : IDL.Nat,
  'customer' : CustomerInfo,
  'orderStatus' : OrderStatus,
  'userId' : IDL.Opt(IDL.Principal),
  'createdAt' : IDL.Int,
  'gstAmount' : IDL.Nat,
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'customer' : CustomerInfo,
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
});
export const ReviewInput = IDL.Record({
  'text' : IDL.Text,
  'productId' : IDL.Nat,
  'rating' : IDL.Nat,
  'image1' : IDL.Opt(ExternalBlob),
  'image2' : IDL.Opt(ExternalBlob),
  'image3' : IDL.Opt(ExternalBlob),
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'productId' : IDL.Nat,
  'rating' : IDL.Nat,
  'image1' : IDL.Opt(ExternalBlob),
  'image2' : IDL.Opt(ExternalBlob),
  'image3' : IDL.Opt(ExternalBlob),
});
export const ReviewId = IDL.Nat;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'addresses' : IDL.Vec(Address),
  'phone' : IDL.Text,
});
export const InvoiceData = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'codSurcharge' : IDL.Nat,
  'customer' : CustomerInfo,
  'gstNumber' : IDL.Text,
  'orderDate' : IDL.Int,
  'gstAmount' : IDL.Nat,
  'orderId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'companyName' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'companyAddress' : IDL.Text,
  'subtotal' : IDL.Nat,
});
export const ProductRating = IDL.Record({
  'productId' : IDL.Nat,
  'averageRating' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAddress' : IDL.Func([Address], [IDL.Bool], []),
  'adminAddBanner' : IDL.Func([IDL.Text, ExternalBlob], [Banner], []),
  'adminCreateBlogPost' : IDL.Func([BlogInput], [BlogPost], []),
  'adminCreateProduct' : IDL.Func([ProductInput], [Product], []),
  'adminDeleteBanner' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminDeleteBlogPost' : IDL.Func([BlogId], [IDL.Bool], []),
  'adminDeleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'adminGetAnalytics' : IDL.Func([], [IDL.Vec(DailyAnalytics)], ['query']),
  'adminListAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], []),
  'adminListAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'adminUpdateBlogPost' : IDL.Func(
      [BlogId, BlogInput],
      [IDL.Opt(BlogPost)],
      [],
    ),
  'adminUpdateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'adminUpdateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chatbotQuery' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createOrder' : IDL.Func([OrderInput], [Order], []),
  'createReview' : IDL.Func([ReviewInput], [Review], []),
  'deleteReview' : IDL.Func([ReviewId], [IDL.Bool], []),
  'getBestsellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBlogPost' : IDL.Func([BlogId], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvoice' : IDL.Func([OrderId], [IDL.Opt(InvoiceData)], ['query']),
  'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductRating' : IDL.Func([ProductId], [ProductRating], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listReviewsByProduct' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'lookupPincode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'removeAddress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'updatePaymentStatus' : IDL.Func(
      [OrderId, PaymentStatus, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Address = IDL.Record({
    'tag' : IDL.Text,
    'city' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'state' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Banner = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'image' : ExternalBlob,
  });
  const BlogStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const BlogInput = IDL.Record({
    'status' : BlogStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const BlogId = IDL.Nat;
  const BlogPost = IDL.Record({
    'id' : BlogId,
    'status' : BlogStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'updatedAt' : IDL.Int,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const ProductStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'Skincare' : IDL.Null,
    'Haircare' : IDL.Null,
    'Makeup' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'status' : ProductStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'isBestseller' : IDL.Bool,
    'category' : ProductCategory,
    'isNew' : IDL.Bool,
    'price' : IDL.Nat,
    'image1' : IDL.Opt(ExternalBlob),
    'image2' : IDL.Opt(ExternalBlob),
    'image3' : IDL.Opt(ExternalBlob),
    'image4' : IDL.Opt(ExternalBlob),
    'image5' : IDL.Opt(ExternalBlob),
    'image6' : IDL.Opt(ExternalBlob),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProductStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'isBestseller' : IDL.Bool,
    'category' : ProductCategory,
    'isNew' : IDL.Bool,
    'price' : IDL.Nat,
    'image1' : IDL.Opt(ExternalBlob),
    'image2' : IDL.Opt(ExternalBlob),
    'image3' : IDL.Opt(ExternalBlob),
    'image4' : IDL.Opt(ExternalBlob),
    'image5' : IDL.Opt(ExternalBlob),
    'image6' : IDL.Opt(ExternalBlob),
  });
  const ProductId = IDL.Nat;
  const DailyAnalytics = IDL.Record({
    'revenue' : IDL.Nat,
    'date' : IDL.Int,
    'orderCount' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Refunded' : IDL.Null,
    'Paid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'COD' : IDL.Null,
    'Razorpay' : IDL.Null,
  });
  const CustomerInfo = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'codSurcharge' : IDL.Nat,
    'customer' : CustomerInfo,
    'orderStatus' : OrderStatus,
    'userId' : IDL.Opt(IDL.Principal),
    'createdAt' : IDL.Int,
    'gstAmount' : IDL.Nat,
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'customer' : CustomerInfo,
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
  });
  const ReviewInput = IDL.Record({
    'text' : IDL.Text,
    'productId' : IDL.Nat,
    'rating' : IDL.Nat,
    'image1' : IDL.Opt(ExternalBlob),
    'image2' : IDL.Opt(ExternalBlob),
    'image3' : IDL.Opt(ExternalBlob),
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'productId' : IDL.Nat,
    'rating' : IDL.Nat,
    'image1' : IDL.Opt(ExternalBlob),
    'image2' : IDL.Opt(ExternalBlob),
    'image3' : IDL.Opt(ExternalBlob),
  });
  const ReviewId = IDL.Nat;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'addresses' : IDL.Vec(Address),
    'phone' : IDL.Text,
  });
  const InvoiceData = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'codSurcharge' : IDL.Nat,
    'customer' : CustomerInfo,
    'gstNumber' : IDL.Text,
    'orderDate' : IDL.Int,
    'gstAmount' : IDL.Nat,
    'orderId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'companyName' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'companyAddress' : IDL.Text,
    'subtotal' : IDL.Nat,
  });
  const ProductRating = IDL.Record({
    'productId' : IDL.Nat,
    'averageRating' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAddress' : IDL.Func([Address], [IDL.Bool], []),
    'adminAddBanner' : IDL.Func([IDL.Text, ExternalBlob], [Banner], []),
    'adminCreateBlogPost' : IDL.Func([BlogInput], [BlogPost], []),
    'adminCreateProduct' : IDL.Func([ProductInput], [Product], []),
    'adminDeleteBanner' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminDeleteBlogPost' : IDL.Func([BlogId], [IDL.Bool], []),
    'adminDeleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'adminGetAnalytics' : IDL.Func([], [IDL.Vec(DailyAnalytics)], ['query']),
    'adminListAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], []),
    'adminListAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'adminUpdateBlogPost' : IDL.Func(
        [BlogId, BlogInput],
        [IDL.Opt(BlogPost)],
        [],
      ),
    'adminUpdateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'adminUpdateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chatbotQuery' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createOrder' : IDL.Func([OrderInput], [Order], []),
    'createReview' : IDL.Func([ReviewInput], [Review], []),
    'deleteReview' : IDL.Func([ReviewId], [IDL.Bool], []),
    'getBestsellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBlogPost' : IDL.Func([BlogId], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvoice' : IDL.Func([OrderId], [IDL.Opt(InvoiceData)], ['query']),
    'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductRating' : IDL.Func([ProductId], [ProductRating], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listReviewsByProduct' : IDL.Func(
        [ProductId],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'lookupPincode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'removeAddress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'updatePaymentStatus' : IDL.Func(
        [OrderId, PaymentStatus, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };