/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: bigint;
    status: ProductStatus;
    name: string;
    createdAt: bigint;
    description: string;
    stock: bigint;
    isBestseller: boolean;
    category: ProductCategory;
    isNew: boolean;
    price: bigint;
    image1?: ExternalBlob;
    image2?: ExternalBlob;
    image3?: ExternalBlob;
    image4?: ExternalBlob;
    image5?: ExternalBlob;
    image6?: ExternalBlob;
}
export interface Address {
    tag: string;
    city: string;
    line1: string;
    line2: string;
    state: string;
    pincode: string;
}
export interface OrderItem {
    name: string;
    productId: bigint;
    quantity: bigint;
    price: bigint;
}
export interface OrderInput {
    paymentMethod: PaymentMethod;
    customer: CustomerInfo;
    razorpayOrderId?: string;
    items: Array<OrderItem>;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type BlogId = bigint;
export type ReviewId = bigint;
export interface Review {
    id: bigint;
    userId: Principal;
    createdAt: bigint;
    text: string;
    productId: bigint;
    rating: bigint;
    image1?: ExternalBlob;
    image2?: ExternalBlob;
    image3?: ExternalBlob;
}
export interface InvoiceData {
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    codSurcharge: bigint;
    customer: CustomerInfo;
    gstNumber: string;
    orderDate: bigint;
    gstAmount: bigint;
    orderId: bigint;
    totalAmount: bigint;
    companyName: string;
    items: Array<OrderItem>;
    companyAddress: string;
    subtotal: bigint;
}
export interface ProductInput {
    status: ProductStatus;
    name: string;
    description: string;
    stock: bigint;
    isBestseller: boolean;
    category: ProductCategory;
    isNew: boolean;
    price: bigint;
    image1?: ExternalBlob;
    image2?: ExternalBlob;
    image3?: ExternalBlob;
    image4?: ExternalBlob;
    image5?: ExternalBlob;
    image6?: ExternalBlob;
}
export interface BlogPost {
    id: BlogId;
    status: BlogStatus;
    title: string;
    content: string;
    createdAt: bigint;
    slug: string;
    author: string;
    coverImage?: ExternalBlob;
    updatedAt: bigint;
    excerpt: string;
    category: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    id: bigint;
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    codSurcharge: bigint;
    customer: CustomerInfo;
    orderStatus: OrderStatus;
    userId?: Principal;
    createdAt: bigint;
    gstAmount: bigint;
    razorpayOrderId?: string;
    totalAmount: bigint;
    items: Array<OrderItem>;
    subtotal: bigint;
}
export interface ProductRating {
    productId: bigint;
    averageRating: bigint;
    reviewCount: bigint;
}
export interface Banner {
    id: bigint;
    name: string;
    createdAt: bigint;
    image: ExternalBlob;
}
export interface BlogInput {
    status: BlogStatus;
    title: string;
    content: string;
    slug: string;
    author: string;
    coverImage?: ExternalBlob;
    excerpt: string;
    category: string;
}
export interface DailyAnalytics {
    revenue: bigint;
    date: bigint;
    orderCount: bigint;
}
export interface CustomerInfo {
    city: string;
    name: string;
    email: string;
    state: string;
    addressLine1: string;
    addressLine2: string;
    phone: string;
    pincode: string;
}
export type ProductId = bigint;
export interface ReviewInput {
    text: string;
    productId: bigint;
    rating: bigint;
    image1?: ExternalBlob;
    image2?: ExternalBlob;
    image3?: ExternalBlob;
}
export interface UserProfile {
    name: string;
    email: string;
    addresses: Array<Address>;
    phone: string;
}
export type OrderId = bigint;
export enum BlogStatus {
    published = "published",
    draft = "draft"
}
export enum OrderStatus {
    Delivered = "Delivered",
    Cancelled = "Cancelled",
    Shipped = "Shipped",
    Pending = "Pending"
}
export enum PaymentMethod {
    COD = "COD",
    Razorpay = "Razorpay"
}
export enum PaymentStatus {
    Failed = "Failed",
    Refunded = "Refunded",
    Paid = "Paid",
    Pending = "Pending"
}
export enum ProductCategory {
    Skincare = "Skincare",
    Haircare = "Haircare",
    Makeup = "Makeup"
}
export enum ProductStatus {
    active = "active",
    inactive = "inactive"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addAddress(address: Address): Promise<boolean>;
    adminAddBanner(name: string, image: ExternalBlob): Promise<Banner>;
    adminCreateBlogPost(input: BlogInput): Promise<BlogPost>;
    adminCreateProduct(input: ProductInput): Promise<Product>;
    adminDeleteBanner(id: bigint): Promise<boolean>;
    adminDeleteBlogPost(id: BlogId): Promise<boolean>;
    adminDeleteProduct(id: ProductId): Promise<boolean>;
    adminGetAnalytics(): Promise<Array<DailyAnalytics>>;
    adminListAllBlogPosts(): Promise<Array<BlogPost>>;
    adminListAllOrders(): Promise<Array<Order>>;
    adminUpdateBlogPost(id: BlogId, input: BlogInput): Promise<BlogPost | null>;
    adminUpdateOrderStatus(id: OrderId, status: OrderStatus): Promise<boolean>;
    adminUpdateProduct(id: ProductId, input: ProductInput): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    chatbotQuery(userMessage: string): Promise<string>;
    createOrder(input: OrderInput): Promise<Order>;
    createReview(input: ReviewInput): Promise<Review>;
    deleteReview(reviewId: ReviewId): Promise<boolean>;
    getBestsellers(): Promise<Array<Product>>;
    getBlogPost(id: BlogId): Promise<BlogPost | null>;
    getBlogPostBySlug(slug: string): Promise<BlogPost | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInvoice(id: OrderId): Promise<InvoiceData | null>;
    getNewArrivals(): Promise<Array<Product>>;
    getOrder(id: OrderId): Promise<Order | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    getProductRating(productId: ProductId): Promise<ProductRating>;
    getProductsByCategory(category: ProductCategory): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listActiveProducts(): Promise<Array<Product>>;
    listBanners(): Promise<Array<Banner>>;
    listBlogPosts(): Promise<Array<BlogPost>>;
    listMyOrders(): Promise<Array<Order>>;
    listProducts(): Promise<Array<Product>>;
    listReviewsByProduct(productId: ProductId): Promise<Array<Review>>;
    lookupPincode(pincode: string): Promise<string>;
    removeAddress(index: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: {
        context: Uint8Array;
        response: {
            status: bigint;
            body: Uint8Array;
            headers: Array<{
                value: string;
                name: string;
            }>;
        };
    }): Promise<{
        status: bigint;
        body: Uint8Array;
        headers: Array<{
            value: string;
            name: string;
        }>;
    }>;
    updatePaymentStatus(id: OrderId, status: PaymentStatus, razorpayOrderId: string | null): Promise<boolean>;
}
import type { Banner as _Banner, BlogId as _BlogId, BlogInput as _BlogInput, BlogPost as _BlogPost, BlogStatus as _BlogStatus, CustomerInfo as _CustomerInfo, ExternalBlob as _ExternalBlob, InvoiceData as _InvoiceData, Order as _Order, OrderInput as _OrderInput, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, Product as _Product, ProductCategory as _ProductCategory, ProductInput as _ProductInput, ProductStatus as _ProductStatus, Review as _Review, ReviewInput as _ReviewInput, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addAddress(arg0: Address): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAddress(arg0);
            return result;
        }
    }
    async adminAddBanner(arg0: string, arg1: ExternalBlob): Promise<Banner> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddBanner(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Banner_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddBanner(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Banner_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateBlogPost(arg0: BlogInput): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateBlogPost(await to_candid_BlogInput_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BlogPost_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateBlogPost(await to_candid_BlogInput_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BlogPost_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateProduct(await to_candid_ProductInput_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateProduct(await to_candid_ProductInput_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteBanner(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteBanner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteBanner(arg0);
            return result;
        }
    }
    async adminDeleteBlogPost(arg0: BlogId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteBlogPost(arg0);
            return result;
        }
    }
    async adminDeleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProduct(arg0);
            return result;
        }
    }
    async adminGetAnalytics(): Promise<Array<DailyAnalytics>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAnalytics();
            return result;
        }
    }
    async adminListAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllBlogPosts();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllBlogPosts();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllOrders();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllOrders();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateBlogPost(arg0: BlogId, arg1: BlogInput): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateBlogPost(arg0, await to_candid_BlogInput_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateBlogPost(arg0, await to_candid_BlogInput_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOrderStatus(arg0, to_candid_OrderStatus_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOrderStatus(arg0, to_candid_OrderStatus_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminUpdateProduct(arg0: ProductId, arg1: ProductInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProduct(arg0, await to_candid_ProductInput_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProduct(arg0, await to_candid_ProductInput_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async chatbotQuery(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.chatbotQuery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chatbotQuery(arg0);
            return result;
        }
    }
    async createOrder(arg0: OrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_OrderInput_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_OrderInput_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReview(arg0: ReviewInput): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(await to_candid_ReviewInput_n54(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Review_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(await to_candid_ReviewInput_n54(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Review_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteReview(arg0: ReviewId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async getBestsellers(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestsellers();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestsellers();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: BlogId): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostBySlug(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostBySlug(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostBySlug(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: OrderId): Promise<InvoiceData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewArrivals(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewArrivals();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewArrivals();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductRating(arg0: ProductId): Promise<ProductRating> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductRating(arg0);
            return result;
        }
    }
    async getProductsByCategory(arg0: ProductCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveProducts();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveProducts();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBanners(): Promise<Array<Banner>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBanners();
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBanners();
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogPosts();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogPosts();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyOrders();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyOrders();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReviewsByProduct(arg0: ProductId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReviewsByProduct(arg0);
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReviewsByProduct(arg0);
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async lookupPincode(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupPincode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupPincode(arg0);
            return result;
        }
    }
    async removeAddress(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAddress(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async transform(arg0: {
        context: Uint8Array;
        response: {
            status: bigint;
            body: Uint8Array;
            headers: Array<{
                value: string;
                name: string;
            }>;
        };
    }): Promise<{
        status: bigint;
        body: Uint8Array;
        headers: Array<{
            value: string;
            name: string;
        }>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePaymentStatus(arg0: OrderId, arg1: PaymentStatus, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n69(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n71(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n69(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n71(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
async function from_candid_Banner_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Banner): Promise<Banner> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_BlogPost_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BlogStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogStatus): BlogStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InvoiceData_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceData): InvoiceData {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ProductStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductStatus): ProductStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Review_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Promise<Review> {
    return await from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): Promise<BlogPost | null> {
    return value.length === 0 ? null : await from_candid_BlogPost_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceData]): InvoiceData | null {
    return value.length === 0 ? null : from_candid_InvoiceData_n63(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n35(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: bigint;
    image: _ExternalBlob;
}): Promise<{
    id: bigint;
    name: string;
    createdAt: bigint;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        image: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BlogId;
    status: _BlogStatus;
    title: string;
    content: string;
    createdAt: bigint;
    slug: string;
    author: string;
    coverImage: [] | [_ExternalBlob];
    updatedAt: bigint;
    excerpt: string;
    category: string;
}): Promise<{
    id: BlogId;
    status: BlogStatus;
    title: string;
    content: string;
    createdAt: bigint;
    slug: string;
    author: string;
    coverImage?: ExternalBlob;
    updatedAt: bigint;
    excerpt: string;
    category: string;
}> {
    return {
        id: value.id,
        status: from_candid_BlogStatus_n18(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        slug: value.slug,
        author: value.author,
        coverImage: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.coverImage)),
        updatedAt: value.updatedAt,
        excerpt: value.excerpt,
        category: value.category
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProductStatus;
    name: string;
    createdAt: bigint;
    description: string;
    stock: bigint;
    isBestseller: boolean;
    category: _ProductCategory;
    isNew: boolean;
    price: bigint;
    image1: [] | [_ExternalBlob];
    image2: [] | [_ExternalBlob];
    image3: [] | [_ExternalBlob];
    image4: [] | [_ExternalBlob];
    image5: [] | [_ExternalBlob];
    image6: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    status: ProductStatus;
    name: string;
    createdAt: bigint;
    description: string;
    stock: bigint;
    isBestseller: boolean;
    category: ProductCategory;
    isNew: boolean;
    price: bigint;
    image1?: ExternalBlob;
    image2?: ExternalBlob;
    image3?: ExternalBlob;
    image4?: ExternalBlob;
    image5?: ExternalBlob;
    image6?: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_ProductStatus_n29(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        stock: value.stock,
        isBestseller: value.isBestseller,
        category: from_candid_ProductCategory_n31(_uploadFile, _downloadFile, value.category),
        isNew: value.isNew,
        price: value.price,
        image1: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image1)),
        image2: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image2)),
        image3: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image3)),
        image4: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image4)),
        image5: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image5)),
        image6: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image6))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentStatus: _PaymentStatus;
    paymentMethod: _PaymentMethod;
    codSurcharge: bigint;
    customer: _CustomerInfo;
    orderStatus: _OrderStatus;
    userId: [] | [Principal];
    createdAt: bigint;
    gstAmount: bigint;
    razorpayOrderId: [] | [string];
    totalAmount: bigint;
    items: Array<_OrderItem>;
    subtotal: bigint;
}): {
    id: bigint;
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    codSurcharge: bigint;
    customer: CustomerInfo;
    orderStatus: OrderStatus;
    userId?: Principal;
    createdAt: bigint;
    gstAmount: bigint;
    razorpayOrderId?: string;
    totalAmount: bigint;
    items: Array<OrderItem>;
    subtotal: bigint;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_PaymentStatus_n37(_uploadFile, _downloadFile, value.paymentStatus),
        paymentMethod: from_candid_PaymentMethod_n39(_uploadFile, _downloadFile, value.paymentMethod),
        codSurcharge: value.codSurcharge,
        customer: value.customer,
        orderStatus: from_candid_OrderStatus_n41(_uploadFile, _downloadFile, value.orderStatus),
        userId: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.userId)),
        createdAt: value.createdAt,
        gstAmount: value.gstAmount,
        razorpayOrderId: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.razorpayOrderId)),
        totalAmount: value.totalAmount,
        items: value.items,
        subtotal: value.subtotal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: Principal;
    createdAt: bigint;
    text: string;
    productId: bigint;
    rating: bigint;
    image1: [] | [_ExternalBlob];
    image2: [] | [_ExternalBlob];
    image3: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    userId: Principal;
    createdAt: bigint;
    text: string;
    productId: bigint;
    rating: bigint;
    image1?: ExternalBlob;
    image2?: ExternalBlob;
    image3?: ExternalBlob;
}> {
    return {
        id: value.id,
        userId: value.userId,
        createdAt: value.createdAt,
        text: value.text,
        productId: value.productId,
        rating: value.rating,
        image1: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image1)),
        image2: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image2)),
        image3: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image3))
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: _PaymentStatus;
    paymentMethod: _PaymentMethod;
    codSurcharge: bigint;
    customer: _CustomerInfo;
    gstNumber: string;
    orderDate: bigint;
    gstAmount: bigint;
    orderId: bigint;
    totalAmount: bigint;
    companyName: string;
    items: Array<_OrderItem>;
    companyAddress: string;
    subtotal: bigint;
}): {
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    codSurcharge: bigint;
    customer: CustomerInfo;
    gstNumber: string;
    orderDate: bigint;
    gstAmount: bigint;
    orderId: bigint;
    totalAmount: bigint;
    companyName: string;
    items: Array<OrderItem>;
    companyAddress: string;
    subtotal: bigint;
} {
    return {
        paymentStatus: from_candid_PaymentStatus_n37(_uploadFile, _downloadFile, value.paymentStatus),
        paymentMethod: from_candid_PaymentMethod_n39(_uploadFile, _downloadFile, value.paymentMethod),
        codSurcharge: value.codSurcharge,
        customer: value.customer,
        gstNumber: value.gstNumber,
        orderDate: value.orderDate,
        gstAmount: value.gstAmount,
        orderId: value.orderId,
        totalAmount: value.totalAmount,
        companyName: value.companyName,
        items: value.items,
        companyAddress: value.companyAddress,
        subtotal: value.subtotal
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): BlogStatus {
    return "published" in value ? BlogStatus.published : "draft" in value ? BlogStatus.draft : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): ProductStatus {
    return "active" in value ? ProductStatus.active : "inactive" in value ? ProductStatus.inactive : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Skincare: null;
} | {
    Haircare: null;
} | {
    Makeup: null;
}): ProductCategory {
    return "Skincare" in value ? ProductCategory.Skincare : "Haircare" in value ? ProductCategory.Haircare : "Makeup" in value ? ProductCategory.Makeup : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Failed: null;
} | {
    Refunded: null;
} | {
    Paid: null;
} | {
    Pending: null;
}): PaymentStatus {
    return "Failed" in value ? PaymentStatus.Failed : "Refunded" in value ? PaymentStatus.Refunded : "Paid" in value ? PaymentStatus.Paid : "Pending" in value ? PaymentStatus.Pending : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    COD: null;
} | {
    Razorpay: null;
}): PaymentMethod {
    return "COD" in value ? PaymentMethod.COD : "Razorpay" in value ? PaymentMethod.Razorpay : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Cancelled: null;
} | {
    Shipped: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Cancelled" in value ? OrderStatus.Cancelled : "Shipped" in value ? OrderStatus.Shipped : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n16(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n35(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Banner>): Promise<Array<Banner>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Banner_n9(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Promise<Array<Review>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Review_n56(_uploadFile, _downloadFile, x)));
}
async function to_candid_BlogInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogInput): Promise<_BlogInput> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_BlogStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogStatus): _BlogStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderInput_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInput): _OrderInput {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function to_candid_ProductInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): Promise<_ProductInput> {
    return await to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_ProductStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductStatus): _ProductStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function to_candid_ReviewInput_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewInput): Promise<_ReviewInput> {
    return await to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: BlogStatus;
    title: string;
    content: string;
    slug: string;
    author: string;
    coverImage?: ExternalBlob;
    excerpt: string;
    category: string;
}): Promise<{
    status: _BlogStatus;
    title: string;
    content: string;
    slug: string;
    author: string;
    coverImage: [] | [_ExternalBlob];
    excerpt: string;
    category: string;
}> {
    return {
        status: to_candid_BlogStatus_n14(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        slug: value.slug,
        author: value.author,
        coverImage: value.coverImage ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.coverImage)) : candid_none(),
        excerpt: value.excerpt,
        category: value.category
    };
}
async function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ProductStatus;
    name: string;
    description: string;
    stock: bigint;
    isBestseller: boolean;
    category: ProductCategory;
    isNew: boolean;
    price: bigint;
    image1?: ExternalBlob;
    image2?: ExternalBlob;
    image3?: ExternalBlob;
    image4?: ExternalBlob;
    image5?: ExternalBlob;
    image6?: ExternalBlob;
}): Promise<{
    status: _ProductStatus;
    name: string;
    description: string;
    stock: bigint;
    isBestseller: boolean;
    category: _ProductCategory;
    isNew: boolean;
    price: bigint;
    image1: [] | [_ExternalBlob];
    image2: [] | [_ExternalBlob];
    image3: [] | [_ExternalBlob];
    image4: [] | [_ExternalBlob];
    image5: [] | [_ExternalBlob];
    image6: [] | [_ExternalBlob];
}> {
    return {
        status: to_candid_ProductStatus_n23(_uploadFile, _downloadFile, value.status),
        name: value.name,
        description: value.description,
        stock: value.stock,
        isBestseller: value.isBestseller,
        category: to_candid_ProductCategory_n25(_uploadFile, _downloadFile, value.category),
        isNew: value.isNew,
        price: value.price,
        image1: value.image1 ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image1)) : candid_none(),
        image2: value.image2 ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image2)) : candid_none(),
        image3: value.image3 ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image3)) : candid_none(),
        image4: value.image4 ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image4)) : candid_none(),
        image5: value.image5 ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image5)) : candid_none(),
        image6: value.image6 ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image6)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    customer: CustomerInfo;
    razorpayOrderId?: string;
    items: Array<OrderItem>;
}): {
    paymentMethod: _PaymentMethod;
    customer: _CustomerInfo;
    razorpayOrderId: [] | [string];
    items: Array<_OrderItem>;
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n52(_uploadFile, _downloadFile, value.paymentMethod),
        customer: value.customer,
        razorpayOrderId: value.razorpayOrderId ? candid_some(value.razorpayOrderId) : candid_none(),
        items: value.items
    };
}
async function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    productId: bigint;
    rating: bigint;
    image1?: ExternalBlob;
    image2?: ExternalBlob;
    image3?: ExternalBlob;
}): Promise<{
    text: string;
    productId: bigint;
    rating: bigint;
    image1: [] | [_ExternalBlob];
    image2: [] | [_ExternalBlob];
    image3: [] | [_ExternalBlob];
}> {
    return {
        text: value.text,
        productId: value.productId,
        rating: value.rating,
        image1: value.image1 ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image1)) : candid_none(),
        image2: value.image2 ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image2)) : candid_none(),
        image3: value.image3 ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image3)) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogStatus): {
    published: null;
} | {
    draft: null;
} {
    return value == BlogStatus.published ? {
        published: null
    } : value == BlogStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == ProductStatus.active ? {
        active: null
    } : value == ProductStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    Skincare: null;
} | {
    Haircare: null;
} | {
    Makeup: null;
} {
    return value == ProductCategory.Skincare ? {
        Skincare: null
    } : value == ProductCategory.Haircare ? {
        Haircare: null
    } : value == ProductCategory.Makeup ? {
        Makeup: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivered: null;
} | {
    Cancelled: null;
} | {
    Shipped: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Cancelled ? {
        Cancelled: null
    } : value == OrderStatus.Shipped ? {
        Shipped: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    COD: null;
} | {
    Razorpay: null;
} {
    return value == PaymentMethod.COD ? {
        COD: null
    } : value == PaymentMethod.Razorpay ? {
        Razorpay: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    Failed: null;
} | {
    Refunded: null;
} | {
    Paid: null;
} | {
    Pending: null;
} {
    return value == PaymentStatus.Failed ? {
        Failed: null
    } : value == PaymentStatus.Refunded ? {
        Refunded: null
    } : value == PaymentStatus.Paid ? {
        Paid: null
    } : value == PaymentStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
